### ISSUE TITLE
Invalid tests for Job Sequence are not formatted correctly

### ISSUE THREAD

**Issue by rzuckerm** [TheRenegadeCoder/sample-programs#2938]
These:
```yaml
            sequencing_invalid:
                params:
                   ...
                    -   name: "missing input"
                        input: '"25 15 10 5"'
                        expected: "Usage: please provide a list of profits and a list of deadlines"
                    -   name: "lists different lengths"
                        input: '"1, 2, 3, 4", "1, 2, 3, 4, 5"'
                        expected: "Usage: please provide a list of profits and a list of deadlines"
```
should be like this:
```yaml
            sequencing_invalid:
                params:
                   ...
                    -   name: "missing input"
                        input: '"25, 15, 10, 5"'
                        expected: "Usage: please provide a list of profits and a list of deadlines"
                    -   name: "lists different lengths"
                        input: '"1, 2, 3, 4" "1, 2, 3, 4, 5"'
                        expected: "Usage: please provide a list of profits and a list of deadlines"
```

When I make that change, the following tests fail:
```
FAILED test/generated/test_job_sequencing.py::test_sequencing_invalid[haskell/job-sequencing.hs-lists different lengths] - AssertionError: assert '10' == 'Usage: pleas... of deadlines'
FAILED test/generated/test_job_sequencing.py::test_sequencing_invalid[python/job_sequencing.py-lists different lengths] - AssertionError: assert '10' == 'Usage: pleas... of deadlines'
```
