### ISSUE TITLE
Update README Generation to Credit a Bot Email

### ISSUE THREAD

**Issue by jrg94** [TheRenegadeCoder/sample-programs#4527]
Right now, I think I am being credited every time a README is generated. We should probably update this to a generic bot commit, such as ActionsBot or something else. Should be a simple change (famous last words)!

See https://github.com/TheRenegadeCoder/sample-programs/pull/4526 as an example. I guess I am getting credit for the pull request.

**Comment by jrg94** [comment]
I'm peeking at the workflow now, and the only thing that potentially points back to me is the personal access token (i.e., PAT).

**Comment by jrg94** [comment]
I'm looking at the sample blow which credits github actions with the pull request. Maybe we also need to set the author field? 
```yaml
jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Make changes to pull request
        run: date +%s > report.txt

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.PAT }}
          commit-message: Update report
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: example-patches
          delete-branch: true
          title: '[Example] Update report'
          body: |
            Update report
            - Updated with *today's* date
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            report
            automated pr
          assignees: peter-evans
          reviewers: peter-evans
          team-reviewers: |
            developers
            qa-team
          milestone: 1
          draft: false
```
